### PR TITLE
feat: New `tbl_nrow()` to support lazy data frames

### PR DESCRIPTION
**Pull request by krlmlr**
Necessary for duckplyr because `dim(x)` still dispatches to `dim.data.frame()` for subclasses of `"data.frame"` .

Includes other refactorings.

### CODE REVIEW

**Comment by hadley** [comment]
Would you mind pulling the style changes into a separate PR? That would make it easier to see what you're proposing here.

**Comment by krlmlr** [comment]
The important commit is the last one, ba184c34 . You could take a look at that, I'll also split this PR.

**Review by hadley — APPROVED** [review]
Oh ok that's super simple. Looks fine to me.

**Review by DavisVaughan — COMMENTED** [review]
Nice! ✅

**Pull request merged**
