### PR TITLE
Remove pillar_na() compatibility hack

### PR DESCRIPTION
**Pull request by krlmlr**
Might break AMR, see https://github.com/msberends/AMR/issues/26.

### CODE REVIEW

**Comment by msberends** [comment]
Thanks! Just at the point of releasing a new version, so I’ll quickly update our code!

**Comment by krlmlr** [comment]
Thanks for the heads-up! I'll merge when the AMR update is on CRAN.

**Comment by msberends** [comment]
All good! AMR 1.6.0 is on CRAN, which fixes this.

**Comment by krlmlr** [comment]
Thanks for the heads-up!

**Pull request merged**
