### PR TITLE
Better format for 0-col tibble and matrix columns

### LINKED ISSUE #149: 0-column sub-tibbles are shown as logical
``` r
pillar::colonnade(list(a = 1:3, b = tibble::tibble(.rows = 3)))
#>       a b    
#>   <int> <lgl>
#> 1     1 NA   
#> 2     2 NA   
#> 3     3 NA
```

<sup>Created on 2019-02-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

From https://github.com/tidyverse/tibble/issues/568, CC @yutannihilation.

### PR DESCRIPTION
**Pull request by krlmlr**
Proposing the following output for a column that itself contains a zero-column object:

``` r
tibble::tibble(a = 1:3, b = tibble::tibble(.rows = 3), c = diag(3)[, 0], d = 2:4)
#> # A tibble: 3 x 4
#>       a b     c         d
#>   <int> <===> <===> <int>
#> 1     1                 2
#> 2     2                 3
#> 3     3                 4
```

<sup>Created on 2019-05-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

It renders much nicer with Fira Code.

Closes #149.

### CODE REVIEW

**Comment by hadley** [comment]
To me, the ` <===>` feels too wide and not very descriptive. Couldn't it use the default type annotation? Alternatively, we could just not print it and it include in the list of extra columns?

**Comment by krlmlr** [comment]
Love it, it's 1-2 characters more, though. I think we should preserve the column order, so moving down to "more columns" wouldn't work.

``` r
tibble::tibble(a = 1:3, b = tibble::tibble(.rows = 3), c = diag(3)[, 0], d = 2:4)
#> # A tibble: 3 x 4
#>       a b        c             d
#>   <int> <df[,0]> <dbl[,0]> <int>
#> 1     1                        2
#> 2     2                        3
#> 3     3                        4
```

<sup>Created on 2019-05-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by krlmlr** [comment]
Do we need anything in the shaft? Empty columns at the very right look awkward otherwise.

**Comment by hadley** [comment]
I think it's fine to be a bit wider, since they're not that common. Similarly, for now, I think it's fine to leave empty and we can resolve in the future if we come up with a compelling visualisation of emptiness.

**Pull request merged**
