### PR TITLE
chore: workaround no longer needed for pkgdown 2.1

### LINKED ISSUE #720: pkgdown error with type_sum.accel
The most recent release of pillar seems to coincide with errors on recent package deployments across GitHub Pages. Calling `library(dplyr)` in a pkgdown article is enough to return the following error:

```
#> Error in get(paste0(generic, ".", class), envir = get_method_env()) : 
#>   object 'type_sum.accel' not found
```

There's some good and bad here. The error doesn't stop deployment, which is good. But the error does silently print on pkgdown pages that don't hide library calls behind an `include=FALSE` chunk option in RMarkdown, and that's bad, because it can be hard to notice. Here's a sampling of some recently updated project pages that show the problem (as of 23-12-2024):

1. https://pillar.r-lib.org/articles/extending.html
2. https://docs.ropensci.org/qualR/articles/qualr.html
3. https://docs.ropensci.org/targets/reference/tar_renv.html
4. https://docs.ropensci.org/USAboundaries/articles/usaboundaries-sample-analysis.html
5. https://insightrx.github.io/PKPDsim/articles/error.html
6. https://strengejacke.github.io/ggeffects/articles/introduction_randomeffects.html
7. https://nickch-k.github.io/vtable/articles/vtablefunction.html
8. https://philippemichel.github.io/baseph/articles/my-vignette.html
9. https://takeshinishimura.github.io/fude/articles/additional.html
10. https://ahaeusser.github.io/tscv/articles/vignette_02_cross_validation.html

My best guess is that the problem was introduced by https://github.com/r-lib/pillar/commit/6f6565b5dc30769cab9cb58791e2c6ab5aa83f99 since it wasn't a problem before pillar's most recent CRAN update.

### PR DESCRIPTION
**Pull request by olivroy**
Trying to render a Quarto vignette today, I got:

```r
Error in get(paste0(generic, ".", class), envir = get_method_env()) : 
  object 'type_sum.accel' not found
Output created: ..\..\..\..\AppData\Local\Temp\Rtmpeg0nPL\pkgdown-quarto-2d035aa1f9f\gt-visual.html
```

Since the mentioned issue is fixed, we can remove this?
https://github.com/r-lib/pkgdown/issues/1540.

I may have been mistaken. https://github.com/r-lib/pkgdown/issues/2188 is the issue that got fixed recently. 

Closes #720.

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks. Does Quarto set the `IN_PKGDOWN` environment variable, or what is happening here?

**Comment by olivroy** [comment]
Hmm, it is just that pkgdown now supports Quarto vignettes. So I am giving it a test.


Basically, in one of my packages, I have this quarto article.
````qmd
---
title: "gt visual tests"
format: html
editor: source
code-link: true
toc: true
html-table-processing: none
code-fold: true
---
````

And when I use `pkgdown::build_article('my-article", quiet = FALSE)`, I get the error I mentioned. (this is why Quarto is setting th IN_PKGDOWN envvar.

Should I look for anything in particular?

**Comment by olivroy** [comment]
Maybe pillar could simply use `#' @exportS3method` instead of `s3_register()` if it can depend on R 3.6?

**Comment by krlmlr** [comment]
I'd like to better understand the issue. Does it really have to be a Quarto vignette, or is a Quarto article sufficient (perhaps externally setting the `IN_PKGDOWN` environment variable)? Why is rmarkdown not affected?

**Comment by olivroy** [comment]
I am trying to build / preview a quarto article locally. I didn't encounter issues on GitHub actions.

It seems like IN_PKGDOWN is set for a longer period, and then I get an error somewhere in `quarto_render()`.

I don't fully understand the interactions between all those components.

For now,  since I didn't encounter issues on gh actions, it doesn't seem worth the trouble.

@hadley may have some ideas of what's going on.

**Comment by krlmlr** [comment]
Removed `type_sum.accel()` .

**Pull request closed without merging**
