### PR TITLE
Export new_vertical()

### LINKED ISSUE #130: pillar_shaft.character() should have optional quote argument
The default should be `TRUE` to indicate that quotes should be automatically where needed. You'd use `quote = FALSE` in the first pass of your `pillar_shaft()` method implementation so you can take advantage of an existing format method:

```R
pillar_shaft.percent <- function(x) {
  pillar::pillar_shaft(format(x), quote = FALSE)
}
```

### PR DESCRIPTION
**Pull request by krlmlr**
Closes #130, because `pillar_shaft.pillar_vertical()` doesn't add quotes.

This is pretty much the same as the `"glue"` class, I wonder if _pillar_ should import _glue_ instead, or if this or a similar class should be provided by _rlang_.

Should the constructor be called `new_vertical()` or `new_pillar_vertical()` if the class is called `"pillar_vertical"` ?

### CODE REVIEW

**Comment by hadley** [comment]
Thinking about this more, maybe `as_pillar.default()` should just do this so you can provide a `format()` method (which you'll need to do for data frames anyway).

**Comment by krlmlr** [comment]
`pillar_shaft.default()` is currently doing (as of very recently):

https://github.com/r-lib/pillar/blob/3fabb4e9108b3e50da72f918de2114dac27d3eed/R/shaft.R#L195-L202

Should it be doing any different?

**Comment by hadley** [comment]
Assuming that doesn't print quotes (as the CRAN version does), I don't think anything else is necessary.

**Comment by krlmlr** [comment]
This would be for other packages that want to use this feature, as you suggested in #130.

**Pull request closed without merging**
