### PR TITLE
fix: Fix printing of very small numbers

### LINKED ISSUE #615: Very small numbers print as `Inf.e-324`
Reprex:
``` r
library(pillar)

pillar(4e-324)
#> <pillar>
#>     <dbl>
#> Inf.e-324
```
This looks similar to https://github.com/tidyverse/tibble/issues/377, which was previously closed at https://github.com/r-lib/pillar/commit/d3e1384f6bc75b27f94d6119020b26bc20452729.

### PR DESCRIPTION
**Pull request by krlmlr**
This variant seems to be slightly more numerically stable than the `exp()` variant.

``` r
pillar::pillar(4e-324)
#> <pillar>
#>     <dbl>
#> 4.94e-324
```

<sup>Created on 2022-10-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Closes #615.

### CODE REVIEW

**Comment by bbolker** [comment]
Nice. Any particular insight into why? (I can see the benefits of a 10- rather than an e-based solution in terms of readability, but not immediately obvious why it would be more numerically stable ...)

**Comment by krlmlr** [comment]
I have no idea, to be honest. But I'm seeing this, on my machine and (for the 10^ variant) on the other machines on GHA:

``` r
x <- c(1e6, 1e3, 1e0, 1e-3, 1e-6)
y <- c(6, 3, 0, -3, -6)

exp(log(x) - y * log(10)) - 1
#> [1] -1.776357e-15 -8.881784e-16  0.000000e+00  8.881784e-16  1.776357e-15
10^(log10(x) - y) - 1
#> [1] 0 0 0 0 0
```

<sup>Created on 2022-10-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bbolker** [comment]
It does seem to be better, but only a little bit better on average:

```r
x <- c(1e6, 1e3, 1e0, 1e-3, 1e-6)
y <- c(6, 3, 0, -3, -6)

## alternate mantissa-finding functions
f1 <- function(x,y) { exp(log(x) - y * log(10)) }
f2 <- function(x,y) { 10^(log10(x) - y) }

r1 <- f1(x,y)
r2 <- f2(x,y)

r1-1
##> [1] -1.776357e-15 -8.881784e-16  0.000000e+00  8.881784e-16  1.776357e-15

r2-1
##> [1] 0 0 0 0 0

## sample random values to try
set.seed(101)
m_vals <- runif(10000, min=1, max = 10)
e_vals <- sample(c(-8, 8), size = 10000, replace=TRUE)
f_vals <- m_vals*10^e_vals

## error (original mantissa vs computed mantissa), log10-scale
e1 <- log10(abs(f1(f_vals, e_vals) - m_vals))
e2 <- log10(abs(f2(f_vals, e_vals) - m_vals))
## proportion of zero error
mean(e1 == -Inf) ## 0.0319
mean(e2 == -Inf) ## 0.0563

## replace -Inf values for plotting purposes
rep_fun <- function(x, r = -18) {
    x[x == -Inf] <- r
    x
}
h_fun <- function(x, ...) {
    hist(rep_fun(x), xlim = c(-18, -13), breaks = 25, axes = FALSE, ...)
    axis(side=2, las = 1)
    axis(side=1, at = seq(-18, -13), labels = c("-Inf", seq(-17, -13)))
}
par(mfrow=c(1,2))
h_fun(e1, main = "exp-based"); h_fun(e2, main = "log10-based")
```

**Comment by krlmlr** [comment]
Thanks. Would you mind running this through reprex so that the plot is included here?

**Comment by krlmlr** [comment]
Also, it's important that the values of the form `x * 10^y` (with x and y small integers) are represented correctly, without introducing decimal digits. The code you posted seems to target a slightly different scenario?

**Comment by bbolker** [comment]
Hmm. I'll address both of those if I get a chance, but I might not (I don't honestly think these differences are practically important, just curious).

**Comment by krlmlr** [comment]
I copied your code to the clipboard, ran `reprex::reprex()` in an R session, and pasted here.

``` r
x <- c(1e6, 1e3, 1e0, 1e-3, 1e-6)
y <- c(6, 3, 0, -3, -6)

## alternate mantissa-finding functions
f1 <- function(x, y) {
  exp(log(x) - y * log(10))
}
f2 <- function(x, y) {
  10^(log10(x) - y)
}

r1 <- f1(x, y)
r2 <- f2(x, y)

r1 - 1
#> [1] -1.776357e-15 -8.881784e-16  0.000000e+00  8.881784e-16  1.776357e-15
## > [1] -1.776357e-15 -8.881784e-16  0.000000e+00  8.881784e-16  1.776357e-15

r2 - 1
#> [1] 0 0 0 0 0
## > [1] 0 0 0 0 0

## sample random values to try
set.seed(101)
m_vals <- runif(10000, min = 1, max = 10)
e_vals <- sample(c(-8, 8), size = 10000, replace = TRUE)
f_vals <- m_vals * 10^e_vals

## error (original mantissa vs computed mantissa), log10-scale
e1 <- log10(abs(f1(f_vals, e_vals) - m_vals))
e2 <- log10(abs(f2(f_vals, e_vals) - m_vals))
## proportion of zero error
mean(e1 == -Inf) ## 0.0319
#> [1] 0.0319
mean(e2 == -Inf) ## 0.0563
#> [1] 0.0563

## replace -Inf values for plotting purposes
rep_fun <- function(x, r = -18) {
  x[x == -Inf] <- r
  x
}
h_fun <- function(x, ...) {
  hist(rep_fun(x), xlim = c(-18, -13), breaks = 25, axes = FALSE, ...)
  axis(side = 2, las = 1)
  axis(side = 1, at = seq(-18, -13), labels = c("-Inf", seq(-17, -13)))
}
par(mfrow = c(1, 2))
h_fun(e1, main = "exp-based")
h_fun(e2, main = "log10-based")
```



<sup>Created on 2022-10-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Pull request merged**
